openapi: 3.0.0

info:
  title: ARGENT Bank API
  description: API documentation for potential Bank API endpoints
  version: 1.0.0
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
servers:
  - url: http://localhost:3001/api/v1
paths:
  /user/transactions/overview:
    get:
      summary: View current balance of all accounts
      tags:
        - Overview
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true

      responses:
        "200":
          description: Operation successful
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
        "503":
          description: Service unavailable

  /user/transactions/detail/{accountId}:
    get:
      summary: View current details of specific account
      tags:
        - Account Details
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
          description: The ID of the account to view details for specific account
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      responses:
        "200":
          description: Operation successful
          schema:
            $ref: "#/definitions/ApiResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden              
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "503":
          description: Service unavailable

  /user/transactions/detail/{accountId}/category:
    put:
      summary: Add items to Select Dropdown
      tags:
        - Category
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
          description: The ID of the account to add category to
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
      responses:
        "200":
          description: Operation successful
        "401":
          description: Unauthorized
        "403":
          description: Forbidden       
        "500":
          description: Internal Server Error
        "503":
          description: Service unavailable

  /user/transactions/detail/{accountId}/notes:
    post:
      summary: Add notes via text input
      tags:
        - Notes
      security:
        - bearerAuth: []

      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
          description: The ID of the account to add notes to

        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                notes:
                  type: string
      responses:
        "200":
          description: Operation successful
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden              
        "500":
          description: Internal Server Error
        "503":
          description: Service unavailable

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    AccountOverview:
      properties:
        accountName:
          type: string
          description: Account name
        availableBalance:
          type: number
          description: Account Balance
    AccountDetails:
      properties:
        accountName:
          type: string
          description: Account Name
        availableBalance:
          type: number
          description: Account Balance
        transactions:
          type: array
          items:
            type: object
            properties:
              transactionDate:
                type: string
                format: date
                description: Date of the transaction
              transactionDescription:
                type: string
                description: Description of transaction
              amount:
                type: number
                description: Transaction amount
              newBalance:
                type: number
                description: New Balance after traansaction
              transactionType:
                type: string
                description: Decription of Type of Transaction
              transactionCategory:
                type: string
                description: Description of Transaction Category
              transactionNotes:
                type: string
                description: Additional Information about Transaction

    AccountDetail:
      type: object
      properties:
        accountId:
          type: string
        balance:
          type: number
        transactions:
          type: array
          items:
            $ref: "#/components/schemas/TransactionDetail"
    TransactionDetail:
      type: object
      properties:
        transactionId:
          type: string
        amount:
          type: number
        date:
          type: string
        type:
          type: string
