openapi: 3.0.0

info:
  title: ARGENT Bank API
  description: API documentation for potential Bank API endpoints
  version: 1.0.0
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
servers:
  - url: http://localhost:3001/api/v1
paths:

  /user/profile/accounts/{accountId}:
    get:
      summary: Overview of specific account
      tags:
        - Individual Account 
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
          description: The ID of the account to view details for specific account
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      responses:
        "200":
          description: Operation successful
 
        "401":
          description: Unauthorized
        "403":
          description: Forbidden              
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "503":
          description: Service unavailable

# ENDPOINT COULD BE USED FOR MODAL THAT DISPLAYS EVERY INDIVIDUAL TRANSACTION
  /user/profile/accounts/{accountId}/transactions/{transactionId}:
    get:
      summary: View  details of specific transation on specific account, could be used to create a modal for each transaction
      tags:
        - Transaction Details
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
          description: The ID of the transaction to view 

        
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      responses:
        "200":
          description: Operation successful
 
        "401":
          description: Unauthorized
        "403":
          description: Forbidden              
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "503":
          description: Service unavailable

  /user/profile/accounts/{accountId}/transcations/{transactionId}/category:
    put:
      summary: Add items to select dropdown
      tags:
        - Category
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
          description: The ID of the account to add category to
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
      responses:
        "200":
          description: Operation successful
        "401":
          description: Unauthorized
        "403":
          description: Forbidden       
        "500":
          description: Internal Server Error
        "503":
          description: Service unavailable

  /user/profile/accounts/{accountId}/transactions/{transactionId}/notes:
    post:
      summary: Add notes via text input
      tags:
        - Notes
      security:
        - bearerAuth: []

      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
          description: The ID of the account to add notes to

        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                notes:
                  type: string
      responses:
        "200":
          description: Operation successful
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden              
        "500":
          description: Internal Server Error
        "503":
          description: Service unavailable




components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    IndividualAccount:
      type: object
      properties:
        accountId:
          type: string
          description: Account ID
        accountName:
          type: string
          description: Account name
        availableBalance:
          type: number
          description: Account balance
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/TransactionDetail'
    TransactionDetail:
      type: object
      properties:
        transactionId:
          type: string
          description: Transaction ID
        amount:
          type: number
          description: Transaction amount
        date:
          type: string
          format: date
          description: Date of the transaction
        type:
          type: string
          description: Type of transaction
        transactionDescription:
          type: string
          description: Description of transaction
        newBalance:
          type: number
          description: New balance after transaction
        transactionCategory:
          type: string
          description: Description of transaction category
        transactionNotes:
          type: string
          description: Additional information about transaction