openapi: 3.0.0

info:
  title: ARGENT Bank API
  description: API documentation for potential Bank API endpoints
  version: 1.0.0
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
servers:
  - url: http://localhost:3001/api/v1
paths:
  /user/profile/:
    get:
      summary: View current balance of all accounts
      tags:
        - Profile Overview
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true

      responses:
        "200":
          description: Operation successful
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
        "503":
          description: Service unavailable

  /user/profile/{accountId}:
    get:
      summary: Overview of specific account
      tags:
        - Individual Account 
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
          description: The ID of the account to view details for specific account
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      responses:
        "200":
          description: Operation successful
 
        "401":
          description: Unauthorized
        "403":
          description: Forbidden              
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "503":
          description: Service unavailable

# ENDPOINT COULD BE USED FOR MODAL THAT DISPLAYS EVERY INDIVIDUAL TRANSACTION
  # /user/profile/{accountId}/{transactionId}:
  #   get:
  #     summary: View  details of specific transation on specific account
  #     tags:
  #       - Transaction Details
  #     security:
  #       - bearerAuth: []
  #     parameters:
  #       - in: path
  #         name: accountId
  #         required: true
  #         schema:
  #           type: string
  #         description: The ID of the transaction to view 

        
  #       - in: header
  #         name: Authorization
  #         description: Attach Bearer JWT token
  #         required: true
  #     responses:
  #       "200":
  #         description: Operation successful
 
  #       "401":
  #         description: Unauthorized
  #       "403":
  #         description: Forbidden              
  #       "404":
  #         description: Not Found
  #       "500":
  #         description: Internal Server Error
  #       "503":
  #         description: Service unavailable

  /user/profile/{accountId}/{transactionId}/category:
    put:
      summary: Add items to select dropdown
      tags:
        - Category
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
          description: The ID of the account to add category to
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
      responses:
        "200":
          description: Operation successful
        "401":
          description: Unauthorized
        "403":
          description: Forbidden       
        "500":
          description: Internal Server Error
        "503":
          description: Service unavailable

  /user/profile/{accountId}/{transactionId}/notes:
    post:
      summary: Add notes via text input
      tags:
        - Notes
      security:
        - bearerAuth: []

      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string
          description: The ID of the account to add notes to

        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                notes:
                  type: string
      responses:
        "200":
          description: Operation successful
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden              
        "500":
          description: Internal Server Error
        "503":
          description: Service unavailable

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Overview:
      properties:
        accountName:
          type: string
          description: Account name
        availableBalance:
          type: number
          description: Account Balance
    Individual Account:
      properties:
        accountId:
          type:string
        accountName:
          type: string
          description: Account Name
        availableBalance:
          type: number
          description: Account Balance
        transactions:
          type: array
          items:
            type: object
            properties:
              transactionDate:
                type: string
                format: date
                description: Date of the transaction
              transactionDescription:
                type: string
                description: Description of transaction
              amount:
                type: number
                description: Transaction amount
              newBalance:
                type: number
                description: New Balance after traansaction
              transactionType:
                type: string
                description: Decription of Type of Transaction
              transactionCategory:
                type: string
                description: Description of Transaction Category
              transactionNotes:
                type: string
                description: Additional Information about Transaction

    TransactionDetail:
      type: object
      properties:
        transactionId:
          type: string
        amount:
          type: number
        date:
          type: string
        type:
          type: string
